### ISSUE TITLE
Changes on EVP++

### ISSUE THREAD

**Issue by wangjiyuan9** [Lavreniuk/1st-place-solution-in-CVPR-3rd-Monocular-Depth-Estimation#1]
Hi! The competition is finished. I'd like to know what you have done to the original EVP model to win the 3rd MDEC.
Also, I tried to find your email but failed. I'd like to connect with you!
I'm also curious about your latest work: SPIdepth. But the paper seem to say nothing.... Possible to share your modifies?

**Comment by Lavreniuk** [comment]
Hi, @wangjiyuan9. 
here is my email: nick_93@ukr.net
Original EVP demonstrated good results as it is. For what I tried, I have changed BLIPv2 text embeddings to CLIP image embeddings and put them into adapter. Also added new datasets as mentioned in git repo. But at the same time the best submission was received using DepthAnything model due to I think its large dataset pretraining.
According to the SPIdepth I plan to create the git repo for it in 1-2 weeks, so you could run it.

**Comment by wangjiyuan9** [comment]
Thank you for your quick reply!

**Comment by wangjiyuan9** [comment]
Also, I think your results are better than Depth-anything. Because the depth-relevant indexes(MAE) are the best.
